server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset : UTF-8
      enabled: true
      force: true

spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-mysql.sql
  datasource-meta:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: ${META_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  datasource-data:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: ${DATA_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}